# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Examples of \sQuote{magic_enum} use via \pkg{RcppMagicEnum}
#'
#' This example, directly almost verbatim from the upstream \code{README.md}
#' shows several simple usage patterns for enumerations enabled by the package.
#' @examples
#' magic_enum_example()
magic_enum_example <- function() {
    invisible(.Call(`_RcppMagicEnum_magic_enum_example`))
}

